# MIT License
# 
# Copyright (c) 2017-2018 Roxanne Gibson
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# Project Info
site_name: Roxbot
site_author: "Roxanne Gibson"

# Repositroy
repo_name: "roxxers/roxbot"
repo_url: "https://github.com/roxxers/roxbot"

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 Roxanne Gibson'

# Layout
nav:
    - 'Introduction': 'index.md'
    - 'Quick Start': 'quickstart.md'
    - 'Configuring Roxbot': 'config.md'
    - 'Command Documentation': 'commands.md'
    - 'Creating Cogs For Roxbot': 'cogs.md'
    - 'Contributing': 'contributing.md'
    - 'License': 'license.md'


# Customisation
theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/roxxers'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true


